In [42]:

import numpy as np
list_ = [ 1 , 2 , '3' , 4 , '5' ]
array_list = np.array(object = list_)
q1='''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a
code cto print the data types of both the variables.'''
print(q1)
ans1 = 'yes both are different because both has different functions'
print(ans1)
print(type(list_))
print(type(array_list))


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a
code cto print the data types of both the variables.
yes both are different because both has different functions
<class 'list'>
<class 'numpy.ndarray'>


In [43]:
q2='''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.'''
for i in list_:
    print("data type of :",i,'in list : ', type(i))
for i in array_list:
    print("data type of :",i, "in array_list : " , type(i))



data type of : 1 in list :  <class 'int'>
data type of : 2 in list :  <class 'int'>
data type of : 3 in list :  <class 'str'>
data type of : 4 in list :  <class 'int'>
data type of : 5 in list :  <class 'str'>
data type of : 1 in array_list :  <class 'numpy.str_'>
data type of : 2 in array_list :  <class 'numpy.str_'>
data type of : 3 in array_list :  <class 'numpy.str_'>
data type of : 4 in array_list :  <class 'numpy.str_'>
data type of : 5 in array_list :  <class 'numpy.str_'>


In [44]:
q3='''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.'''

print(q3)
print()
array_list = np.array(object = list_, dtype = int)
for i in list_:
    print("data type of :",i,'in list : ', type(i))
print()
for i in array_list:
    print("data type of :",i, "in array_list : " , type(i))


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

data type of : 1 in list :  <class 'int'>
data type of : 2 in list :  <class 'int'>
data type of : 3 in list :  <class 'str'>
data type of : 4 in list :  <class 'int'>
data type of : 5 in list :  <class 'str'>

data type of : 1 in array_list :  <class 'numpy.int32'>
data type of : 2 in array_list :  <class 'numpy.int32'>
data type of : 3 in array_list :  <class 'numpy.int32'>
data type of : 4 in array_list :  <class 'numpy.int32'>
data type of : 5 in array_list :  <class 'numpy.int32'>


In [45]:
q4='''Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print('shape of num_array : ',num_array.shape)
print('size of num_array : ',num_array.size)

shape of num_array :  (2, 3)
size of num_array :  6


In [50]:
q5='''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.'''
npzero=np.zeros((3,3))
print(npzero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
q6='Q6. Create an identity matrix of shape (5,5) using numpy functions?'
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
